### ISSUE TITLE
Clicking "add xxx" on an image block adds at the wrong place

### ISSUE THREAD

**Issue by olance** [algolia/documentation-editor#21] opened 2016-01-13 10:45 UTC
It's hard to say what the bug is exactly, but when I click "Add text" or "Add table" or whatever else on an image block, items are added below another image higher in my doc!

**Comment by pixelastic** [comment] 2016-01-18 09:59
Could you maybe record it as a gif?

**Comment by olance** [comment] 2016-01-26 07:59
@pixelastic sorry I never saw your comment before. I can do that :)

**Comment by olance** [comment] 2016-01-26 08:01
... when I can reproduce it!
There's probably some kind of preliminary condition to make this bug happen, I'll let you know when I get to it!

**Comment by redox** [comment] 2016-02-19 14:39
Closing it for now.

**Closed as completed by redox** 2016-02-19 14:39 UTC

**Comment by olance** [comment] 2016-02-20 11:15
hmm @redox I understand it is not easily reproducible so hard to move forward on the issue, but why close it?
At least the open issue helps remind anyone to keep an eye out for this bug?

**Comment by redox** [comment] 2016-02-20 12:26
If we cannot reproduce a bug, I don't see any value keeping it open. If someone triggers it again, the worst case will be to reopen a new issue instead of appending it to this one, which is not a big deal.

Some projects have even bots doing it.

**Comment by olance** [comment] 2016-02-20 12:57
OK, as you wish. Although the worst case will probably to have a duplicate ^^

**Comment by olance** [comment] 2016-02-20 12:57
OK, as you wish.
